name: widgets_on_fhir_example

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.0.0

dependencies:
  fhir: ^0.4.0
#    git:
#      url: https://github.com/MayJuun/fhir.git
#      path: fhir
#      ref: dev

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  widgets_on_fhir:
    path: ..

dev_dependencies:
  lint: ^1.0.0

flutter:
  uses-material-design: true
