name: faiadashu_example
description: Gallery app for Faiadashu™

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  collection: ^1.15.0

  faiadashu:
    path: ..

  faiadashu_online:
    path: ../faiadashu_online

  fhir: ^0.5.0-12
#  fhir:
#    path: /Users/tilo/Projects/fhir/fhir

  fhir_auth: ^0.5.0-9
#  fhir_auth:
#    path: ../../fhir/fhir_auth

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^2.1.1

  intl: ^0.17.0

  logging: ^1.0.1

  simple_html_css: ^3.0.1

dev_dependencies:
  lint: ^1.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/instruments/
    - assets/valuesets/
    - assets/codesystems/
    - assets/responses/
    - assets/images/
