name: faiadashu_example
description: Example app for Faiadashu™

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  collection: ^1.15.0

  faiadashu:
    path: ..

  fhir: ^0.4.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/instruments/
