name: faiadashu_example
description: Example app for Faiadashu™

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  collection: ^1.15.0

  faiadashu:
    path: ..

  faiadashu_online:
    path: ../faiadashu_online

  fhir: ^0.4.6
#  fhir:
#    path: /Users/tilo/Projects/fhir/fhir

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logging: ^1.0.1

  url_launcher: ^6.0.3

dev_dependencies:
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/instruments/
    - assets/valuesets/
    - assets/codesystems/
    - assets/responses/
    - assets/images/




