include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - example/lib/generated_plugin_registrant.dart

linter:
  rules:
#    require_trailing_commas: false