arb-dir: lib/l10n/arb
template-arb-file: fdash_en.arb
output-dir: lib/l10n/src
synthetic-package: false
output-localization-file: fdash_localizations.g.dart
output-class: FDashLocalizations
nullable-getter: false
header: "// ignore_for_file: avoid_escaping_inner_quotes"
preferred-supported-locales:
  - en

