name: faiadashu_online
description: Faiadashu Online - Functionalities for faiadashu that connect to FHIR(R) servers.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: none

version: 0.6.0-dev.2
homepage: https://tiloc.github.io/faiadashu/
repository: https://github.com/tiloc/faiadashu
issue_tracker: https://github.com/tiloc/faiadashu/issues

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.3'

dependencies:
  faiadashu:
    path: ..

  fhir: ^0.5.0-10
  fhir_auth: ^0.5.0-6

  flutter:
    sdk: flutter
  logging: ^1.0.1

  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.7.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
